### ISSUE TITLE
a problem of resnet50

### ISSUE THREAD

**Issue by zyjiajia** [mohammaduzair9/Style-Classification#2]
Dear author, the file of  resnet50（resnet50_weights_tf_dim_ordering_tf_kernels.h5） does not exist under Style-Classification directory.

**Comment by mohammaduzair9** [comment]
This file is in the folder link under trained model description

**Comment by mohammaduzair9** [comment]
https://drive.google.com/drive/folders/1SmDLcv-8HRbJwqSecHZKL121PishXb1v?usp=sharing

**Comment by mohammaduzair9** [comment]
You must download the resnet50_weights_tf_dim_ordering_tf_kernels.h5 file from this link and place it in the directory Style_Classification
