### ISSUE TITLE
A problem encountered when running the test_frcnn.py

### ISSUE THREAD

**Issue by zyjiajia** [mohammaduzair9/Style-Classification#3]
ValueError: Shape must be rank 1 but is rank 0 for 'bn_conv1/Reshape_4' (op: 'Reshape') with input shapes: [1,1,1,64], [].

**Comment by danish-imam** [comment]
https://github.com/keras-team/keras/commit/e3a2f7d29f2f1c21ecc978bd0038b1d1330d33c2

try making these changes into keras/backend/tensorflow_backend.py
