### ISSUE TITLE
Text detection on documents

### ISSUE THREAD

**Issue by stwykd** [mohammaduzair9/Style-Classification#4]
I cloned your project and tried running it on documents but I'm not getting nice performance in that case.
The text detection part only detects words and it misses a lot text when you give it a inputs text-rich such a documents or books.
How could I change the model to fix this issue?

**Comment by mohammaduzair9** [comment]
The model i am using is trained on scene images and not the documents. You can try changing the training data to documents.

**Comment by sahithi96** [comment]
Hi I am using your project to discriminate between Signatures and Printed text in a document. 
In order to train the data how many image samples of each class are required approximately?
